language: python

# use container-based travis-ci infrastructure
sudo: false

# use legacy infrastructure
#sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"

services:
  - mongodb

install:
  - mkdir -p /tmp/logs/synergy-flow
  - pip install six
  - pip install pymongo
  - pip install synergy_scheduler
  - pip install synergy_odm
  - pip install boto3
  - pip install google-auth-httplib2 google-api-python-client google-cloud-dataproc google-cloud-storage
  - pip install azure-storage-blob

script:
  - python -m unittest discover tests

branches:
  only:
    - master
    - unstable
